import {defineAction} from 'redux-define';
import {
  GET_STEAM_USER_SUMMARY_ACTIONS,
  GET_STEAM_USER_GAMES_LIST_ACTIONS,
} from '../states';

export const GET_STEAM_USER_SUMMARY = defineAction('GET_STEAM_USER_SUMMARY_ACTIONS', GET_STEAM_USER_SUMMARY_ACTIONS);
export const GET_STEAM_USER_GAMES_LIST = defineAction('GET_STEAM_USER_GAMES_LIST_ACTIONS', GET_STEAM_USER_GAMES_LIST_ACTIONS);
